#***********************
# Even Fibonacci numbers
# Problem 2
#***********************

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# **********************
# Thoughts:
  # define how to make next fib number
  # add the next fib numbers to array until the value exceeds 4 million
  # loop through array, check if even. if so add value to sum variable
  # return sum
# **********************


def make_next
  array = [1, 2, 3, 5]
  next_up = array[-1] + array[-2]
  array << next_up
end

while next_up < 4000000
  array << next_up
end

sum = 0
array.each do |i|
  if i % 2 == 0
    sum += i
  end
end
